name = "fire-control"
author = "Sliden"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29bcf953b90081730cd8a32cc4d855ab6ad96685c3aeea6ed033dc4f04d390ac"

[versions]
minecraft = "1.20.1"
forge = "47.2.32"
